# -*- mode: ruby -*-
# vi: set ft=ruby :

# box name into env var, same script can be used with different boxes.
# Default: IE8.Win7.
box_name = ENV['box_name'].nil? ? 'IE8.Win7' : ENV['box_name'].strip
# box repo into env var, so private repos/cache can be used.
# Default: http://aka.ms
box_repo = ENV['box_repo'].nil? ? 'http://aka.ms' : ENV['box_repo'].strip

Vagrant.configure('2') do |config|
  # If the box is win7-ie11, the convention for the box name
  # is modern.ie/win7-ie11
  config.vm.box = 'modern.ie/' + box_name
  # If the box is win7-ie11, the convention for the box url
  # is http://aka.ms/vagrant-win7-ie11
  config.vm.box_url = box_repo + '/vagrant-' + box_name
  # big timeout since windows boot is very slow
  config.vm.boot_timeout = 500

  # rdp forward
  config.vm.network 'forwarded_port', guest: 3389, host: 3389,
                                      id: 'rdp', auto_correct: true

  # winrm config, uses modern.ie default user/password. If other
  # credentials are used must be changed here
  config.vm.communicator = 'winrm'
  config.winrm.username = 'IEUser'
  config.winrm.password = 'Passw0rd!'

  config.vm.provider 'virtualbox' do |vb|
    # first setup requires gui to be enabled so scripts can be executed
    # in virtualbox guest screen
    # vb.gui = true
    #
    vb.customize ['modifyvm', :id, '--memory', '1024']
    vb.customize ['modifyvm', :id, '--vram', '128']
    vb.customize ['modifyvm', :id, '--cpus', '2']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['guestproperty', 'set', :id,
                  '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold',
                  10_000]
  end
end
