version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
